---
abstract: 'Perl interface to pselect(2)'
author:
  - 'Fuji, Goro (gfx) <gfuji@cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0.06
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: POSIX::pselect
name: POSIX-pselect
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-POSIX-pselect.git
version: 0.03
